# Generated by Django 5.0.6 on 2024-06-26 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DesignerHubApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='like_designs',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
