# Generated by Django 5.0.6 on 2024-08-14 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesignerHubApp', '0004_userbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DesignerHubApp.designerwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DesignerHubApp.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='DesigneWorkReview',
        ),
    ]
